name: Build and Push to Docker Hub

# Trigger the build every time code is pushed to the main branch
# Don't trigger on certain paths (paths-ignore)
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**.md'           # Ignores any other markdown files in the repo
      - '.gitignore'      # Ignores updates to git ignore list
      - 'LICENSE'         # Ignores license updates

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download code from GitHub onto the builder runner
      # actions/checkout@v6.0.2
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # Step 2: Log into Docker Hub account
      # docker/login-action@v4.2.0
      - name: Log in to Docker Hub 
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # docker/build-push-action@v7.1.0
      - name: Build and Push Docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gpxposterprint:latest
