name: Build and Push to Docker Hub

# Trigger the build every time code is pushed to the main branch
# Don't trigger on certain paths (paths-ignore)
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**.md'           # Ignores any other markdown files in the repo
      - '.gitignore'      # Ignores updates to git ignore list
      - 'LICENSE'         # Ignores license updates

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download code from GitHub onto the builder runner
      # actions/checkout@v6.0.3 (Latest v6 release)
      - name: Checkout code
        uses: actions/checkout@1af3b93f4e2dbef7bb99f27914bfcb83aefc3332 # v6.0.3

      # Step 2: Log into Docker Hub account
      # docker/login-action@v4.2.0 (Latest v4 release)
      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6da5462943896b02008ebec949a3c9a622a # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # docker/build-push-action@v7.0.0 (Latest v7 release)
      - name: Build and Push Docker image
        uses: docker/build-push-action@70b202fbff626fbef0be357a73fc5ccfdd37f075 # v7.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gpxposterprint:latest
